version: '2'

services:
  db:
    image: mysql:8.0
    networks:
      - ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - ./mysql-data:/var/lib/mysql
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - ecommerce
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/ecommerce
      SPRING_DATASOURCE_USERNAME: ecommerce
      SPRING_DATASOURCE_PASSWORD: 1234
networks:
  ecommerce:
    driver: bridge
